# Generated by Django 4.2.7 on 2023-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0002_alter_news_options_alter_news_news_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons_title_uz', models.CharField(max_length=300, verbose_name="E'lon sarlavhasi")),
                ('anons_title_en', models.CharField(max_length=300, verbose_name='Announcement title')),
                ('anons_title_ru', models.CharField(max_length=300, verbose_name='Заголовок объявление')),
                ('anons_desc_uz', models.CharField(max_length=500, verbose_name="E'lon qisqacha tavsifi")),
                ('anons_desc_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Announcement description')),
                ('anons_desc_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание объявление')),
                ('anons_datetime', models.DateTimeField(auto_now_add=True)),
                ('anons_deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'pr_anons',
                'ordering': ('-anons_datetime',),
            },
        ),
    ]
