# Generated by Django 4.2.7 on 2023-12-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0003_anons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name_uz', models.CharField(max_length=100, verbose_name='Vakansiya nomi')),
                ('vacancy_name_en', models.CharField(max_length=100, verbose_name='Vacancy name')),
                ('vacancy_name_ru', models.CharField(max_length=100, verbose_name='Названия ваканcия')),
                ('vacancy_desc_uz', models.CharField(max_length=500, verbose_name='Vakansiya qisqacha tavsifi')),
                ('vacancy_desc_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vacancy description')),
                ('vacancy_desc_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание вакансия')),
                ('vacancy_text_uz', models.TextField(verbose_name='Vakansiya to‘liq tavsifi')),
                ('vacancy_text_en', models.TextField(blank=True, null=True, verbose_name='Vacancy full text')),
                ('vacancy_text_ru', models.TextField(blank=True, null=True, verbose_name='Польное описания вакансия')),
                ('vacancy_datetime', models.DateTimeField(auto_now_add=True)),
                ('vacancy_views_count', models.IntegerField(default=0, verbose_name='Ko‘rishlar soni')),
                ('vacancy_status', models.BooleanField(default=True, verbose_name='Vakansiya holati')),
            ],
            options={
                'db_table': 'pr_vacancies',
                'ordering': ('-vacancy_datetime',),
            },
        ),
    ]
