# Generated by Django 4.2.7 on 2023-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0005_image_photogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
            ],
            options={
                'db_table': 'gallery_videos_links',
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title_uz', models.CharField(max_length=255, verbose_name='Videogalereya sarlavhasi')),
                ('gallery_title_en', models.CharField(max_length=255, verbose_name='Title videogallery')),
                ('gallery_title_ru', models.CharField(max_length=255, verbose_name='Названия видеогалерея')),
                ('gallery_desc_uz', models.CharField(max_length=500, verbose_name='Videogalereya qisqacha tavsifi')),
                ('gallery_desc_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Videogallery description')),
                ('gallery_desc_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание видеогалерея')),
                ('gallery_datetime', models.DateTimeField(auto_now_add=True)),
                ('gallery_views_count', models.IntegerField(default=0, verbose_name='Ko‘rishlar soni')),
                ('gallery_videos', models.ManyToManyField(to='app_piar.videolinks')),
            ],
            options={
                'db_table': 'pr_videogallery',
                'ordering': ('-gallery_datetime',),
            },
        ),
    ]
