# Generated by Django 4.2.7 on 2023-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0007_news_news_desc_news_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
