# Generated by Django 4.2.7 on 2023-12-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0008_news_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_desc',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_title',
        ),
    ]
