# Generated by Django 4.2.7 on 2023-12-19 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_piar', '0010_news_news_desc_news_news_text_news_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_author',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
