# Generated by Django 4.2.7 on 2023-12-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_uz', models.CharField(max_length=255, verbose_name='Maktab nomi')),
                ('school_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='School name')),
                ('school_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название школы')),
                ('school_logo', models.ImageField(upload_to='school/')),
                ('school_address_uz', models.TextField(verbose_name='Maktab adresi')),
                ('school_address_en', models.TextField(blank=True, null=True, verbose_name='School address')),
                ('school_address_ru', models.TextField(blank=True, null=True, verbose_name='Адрес школы')),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('school_phone', models.CharField(blank=True, null=True, verbose_name='Telefon')),
                ('school_prime_times', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qabul vaqtlari')),
                ('school_location_lat', models.CharField(blank=True, max_length=15, null=True, verbose_name='Latitude')),
                ('school_location_lon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitude')),
                ('school_smm_tg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram')),
                ('school_smm_fb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook')),
                ('school_smm_ig', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram')),
                ('school_smm_yt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Youtube')),
            ],
            options={
                'db_table': 'school_infos',
            },
        ),
    ]
