# Generated by Django 4.2.7 on 2023-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutschool',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
    ]
